# Generated by Django 3.1.2 on 2021-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('maximum', models.IntegerField(default=0)),
                ('minimum', models.IntegerField(default=0)),
            ],
        ),
    ]
